in_channels: 99
learning_rate: 0.001
model_params:
  accelerator: gpu
  batch_size: 8
  depth: 2
  devices: 1
  embedding_size: 64
  in_channels: 99
  kernel_size: 3
  learning_rate: 0.001
  max_epochs: 5
  model_type: SegmentationCNN
  n_encoders: 2
  num_workers: 11
  out_channels: 4
  pool_sizes: 5,5,2
  processed_dir: !!python/object/apply:pathlib.WindowsPath
  - C:\
  - Users
  - Bhavya Gupta
  - Documents
  - School
  - CS175
  - hw03-segmentation-hungry-hungry-hippo
  - data
  - processed
  - 4x4
  raw_dir: !!python/object/apply:pathlib.WindowsPath
  - C:\
  - Users
  - Bhavya Gupta
  - Documents
  - School
  - CS175
  - hw03-segmentation-hungry-hungry-hippo
  - data
  - raw
  - Train
  scale_factor: 50
  seed: 12378921
  selected_bands: null
  tile_size_gt: 4
  wandb_run_name: null
model_type: SegmentationCNN
out_channels: 4
